server:
  port: 8080

stats-server:
  url: ${STATS_SERVER_URL:http://stats-server:9090}
  app-name: ${STATS_SERVER_APP_NAME:ewm-main-service}

spring:
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm
    username: ewm
    password: ewm
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
