--liquibase formatted sql

--changeset practicum:1
CREATE TABLE IF NOT EXISTS users (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email)
);

--changeset practicum:2
CREATE TABLE IF NOT EXISTS categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT uq_category_name UNIQUE (name)
);

--changeset practicum:3
CREATE TABLE IF NOT EXISTS events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation          VARCHAR(2000) NOT NULL,
    description         VARCHAR(7000) NOT NULL,
    title               VARCHAR(120) NOT NULL,
    event_date          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_on          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on        TIMESTAMP WITHOUT TIME ZONE,
    state               VARCHAR(20) NOT NULL,
    paid                BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit   INTEGER NOT NULL DEFAULT 0,
    request_moderation  BOOLEAN NOT NULL DEFAULT TRUE,
    lat                 DOUBLE PRECISION NOT NULL,
    lon                 DOUBLE PRECISION NOT NULL,
    category_id         BIGINT NOT NULL,
    initiator_id        BIGINT NOT NULL,
    CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_event_initiator FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_events_state_event_date ON events (state, event_date);
CREATE INDEX IF NOT EXISTS idx_events_category_id ON events (category_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator_id ON events (initiator_id);

--changeset practicum:4
CREATE TABLE IF NOT EXISTS participation_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status       VARCHAR(20) NOT NULL,
    event_id     BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    CONSTRAINT fk_request_event FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_request_requester FOREIGN KEY (requester_id) REFERENCES users (id),
    CONSTRAINT uq_event_requester UNIQUE (event_id, requester_id)
);

CREATE INDEX IF NOT EXISTS idx_requests_event_status ON participation_requests (event_id, status);

--changeset practicum:5
CREATE TABLE IF NOT EXISTS compilations (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(50) NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_compilation_title UNIQUE (title)
);

--changeset practicum:6
CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation_events_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE,
    CONSTRAINT fk_compilation_events_event FOREIGN KEY (event_id) REFERENCES events (id)
);

--changeset practicum:7
CREATE TABLE IF NOT EXISTS comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR(7000) NOT NULL,
    created    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated    TIMESTAMP WITHOUT TIME ZONE,
    author_id  BIGINT NOT NULL,
    event_id   BIGINT NOT NULL,
    CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_comment_event  FOREIGN KEY (event_id)  REFERENCES events (id)
);

CREATE INDEX IF NOT EXISTS idx_comments_event_id  ON comments (event_id);
CREATE INDEX IF NOT EXISTS idx_comments_author_id ON comments (author_id);
